import 'package:lab_3/task.dart';

const List<Task> tasks = [
  Task(Day.monday, true, id: 1, name: 'Task 1 on Monday'),
  Task(Day.monday, false, id: 2, name: 'Task 2 on Monday'),
  Task(Day.monday, true, id: 3, name: 'Task 3 on Monday'),
  Task(Day.monday, false, id: 4, name: 'Task 4 on Monday'),
  Task(Day.monday, false, id: 5, name: 'Task 5 on Monday'),
  Task(Day.tuesday, false, id: 6, name: 'Task 1 on Tuesday'),
  Task(Day.tuesday, true, id: 7, name: 'Task 2 on Tuesday'),
  Task(Day.tuesday, true, id: 8, name: 'Task 3 on Tuesday'),
  Task(Day.tuesday, true, id: 9, name: 'Task 4 on Tuesday'),
  Task(Day.tuesday, true, id: 10, name: 'Task 5 on Tuesday'),
  Task(Day.wednesday, true, id: 11, name: 'Task 1 on Wednesday'),
  Task(Day.wednesday, true, id: 12, name: 'Task 2 on Wednesday'),
  Task(Day.wednesday, false, id: 13, name: 'Task 3 on Wednesday'),
  Task(Day.wednesday, false, id: 14, name: 'Task 4 on Wednesday'),
  Task(Day.wednesday, true, id: 15, name: 'Task 5 on Wednesday'),
  Task(Day.thursday, false, id: 16, name: 'Task 1 on Thursday'),
  Task(Day.thursday, false, id: 17, name: 'Task 2 on Thursday'),
  Task(Day.thursday, true, id: 18, name: 'Task 3 on Thursday'),
  Task(Day.thursday, false, id: 19, name: 'Task 4 on Thursday'),
  Task(Day.thursday, false, id: 20, name: 'Task 5 on Thursday'),
  Task(Day.friday, true, id: 21, name: 'Task 1 on Friday'),
  Task(Day.friday, false, id: 22, name: 'Task 2 on Friday'),
  Task(Day.friday, true, id: 23, name: 'Task 3 on Friday'),
  Task(Day.friday, false, id: 24, name: 'Task 4 on Friday'),
  Task(Day.friday, true, id: 25, name: 'Task 5 on Friday'),
  Task(Day.saturday, true, id: 26, name: 'Task 1 on Saturday'),
  Task(Day.saturday, true, id: 27, name: 'Task 2 on Saturday'),
  Task(Day.saturday, true, id: 28, name: 'Task 3 on Saturday'),
  Task(Day.saturday, true, id: 29, name: 'Task 4 on Saturday'),
  Task(Day.saturday, true, id: 30, name: 'Task 5 on Saturday'),
  Task(Day.sunday, true, id: 31, name: 'Task 1 on Sunday'),
  Task(Day.sunday, true, id: 32, name: 'Task 2 on Sunday'),
  Task(Day.sunday, true, id: 33, name: 'Task 3 on Sunday'),
  Task(Day.sunday, true, id: 34, name: 'Task 4 on Sunday'),
  Task(Day.sunday, false, id: 35, name: 'Task 5 on Sunday'),
  Task(Day.today, false, id: 36, name: 'Task 1 for today'),
  Task(Day.today, true, id: 37, name: 'Task 2 for today'),
  Task(Day.today, true, id: 38, name: 'Task 3 for today'),
  Task(Day.today, false, id: 39, name: 'Task 4 for today'),
  Task(Day.today, false, id: 40, name: 'Task 5 for today'),
];
